apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "catalogue-db.fullname" . }}
{{- template "catalogue-db.systemlabels" . }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "catalogue-db.selectorLabels" . | nindent 4 }}
