apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
{{- template "carts.systemlabels" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "carts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "carts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        env:
         - name: {{ .Values.env.name }}
           value: {{ .Values.env.value }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .Values.volumeMounts.mountPath }}
          name: {{ .Values.volumeMounts.name }}
      volumes:
{{- toYaml .Values.volumes | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

