apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
spec: 
  type: ClusterIP
  ports:
   - targetPort: {{ .Values.port }}
     port: {{ .Values.port }}
  selector:
     app: {{ .Values.app }}
