apiVersion: v1
kind: Service
metadata: 
  name: 
spec: {{ .Release.Name}}-service
  type: ClusterIP
  ports: 
   - targetPort: {{ .Values.port }}
     port: {{ .Values.port }}
  selector:
     app: {{ .Values.app }}

