apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-microservice-nodejs
  labels:
    app: cart-microservice
spec:
  selector:
      matchLabels:
        app: cart-microservice
  template:
    metadata:
      labels:
        app: cart-microservice
    spec:
      containers:
      - name: cart-microservice
        image: nodejs-webapp  
        imagePullPolicy: IfNotPresent
