# Default values for ui-react.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
#
#
image: shalde064/react-app
imageTag: "latest"
imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

strategy:
  type: Recreate

tolerations: []

livenessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
