apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name}}-label
spec:
  type: {{ .Values.service.type }}
  ports:
   - targetPort: {{ .Values.service.port }}
     port: {{ .Values.service.port }}
  selector:
     app: {{ .Release.Name}}-label
