apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
{{- template "front-end.systemlabels" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "front-end.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-end.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}"
        {{- with .Values.ports }}
        ports:
            containerPort: {{ .containerPort}}
        {{- end }}
        env:
          - name: {{ .Values.env.name | upper }}
            value: {{ .Values.env.value | quote }}
        {{- with .Values.securityContext }}
        securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
