apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
{{- template "front-end.systemlabels" . }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
  {{- end }}
  selector:
    {{- include "carts-db.selectorLabels" . | nindent 4 }}

