apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
  labels:
    app: {{ .Values.app }}
spec:
  selector:
      matchLabels:
        app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.containername }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
