apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "orders.fullname" . }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orders.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orders.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        env:
          - name: {{ .Values.env.name }}
            value: {{ .Values.env.value  }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.ports.containerPort}}
        securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
           - mountPath: {{ .mountPath}}
             name: {{ .name}}
        {{- end }}
      volumes:
{{- toYaml .Values.volumes | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}


