apiVersion: v1
kind: Service 
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "orders.selectorLabels" . | nindent 6 }}
