# Default values for carts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: weaveworksdemos/carts:0.4.8

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
        prometheus.io/scrape: 'true'

env:
  name: JAVA_OPTS
  value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

ports:
  containerPort: 80


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    memory: 500Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes:
  - name: tmp-volume
    emptyDir:
      medium: Memory

volumeMounts:
    mountPath: /tmp
    name: tmp-volume

tolerations: []

affinity: {}
