apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
{{- template "catalogue-helm.systemlabels" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "catalogue-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "catalogue-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}"
        command: [ {{ .Values.command | quote -}} ]
        args:
{{- toYaml .Values.args | nindent 10 }} 
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
         {{-  toYaml . | nindent 8 }}
      {{- end }}
